version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/eventbooking
      - SPRING_DATASOURCE_USERNAME=eventuser
      - SPRING_DATASOURCE_PASSWORD=securepassword
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=eventbooking
      - POSTGRES_USER=eventuser
      - POSTGRES_PASSWORD=securepassword
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U eventuser -d eventbooking" ]
      interval: 5s
      timeout: 5s
      retries: 5