name: Build, Test, and Deploy Event Booking

on: [ push ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'


      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Package Application
        run: mvn package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4

        with:
          name: app-jar
          path: target/*.jar
          retention-days: 1

#  deploy:
#    name: Deploy to Heroku
#    runs-on: ubuntu-latest
#    needs: build
#    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Download JAR artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: app-jar
#          path: target
#
#      - name: Login to Heroku
#        uses: akhileshns/heroku-deploy@v3.12.14
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}
#          justlogin: true
#
#      - name: Deploy to Heroku
#        uses: akhileshns/heroku-deploy@v3.12.14
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}
#          procfile: "web: java -jar target/*.jar --server.port=$PORT $JAVA_OPTS"