name: Build, Test, and Deploy Event Booking

on: [ push ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Package Application
        run: mvn package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          retention-days: 1

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "abdulrahman403828@fci.bu.edu.eg"
          justlogin: true

      - name: Create or Verify Heroku App
        run: |
          if ! heroku apps:info --app ${{ secrets.HEROKU_APP_NAME }} 2>/dev/null; then
            heroku create ${{ secrets.HEROKU_APP_NAME }}
            echo "Created new Heroku app"
          else
            echo "Heroku app already exists"
          fi

      - name: Add Heroku Postgres
        run: |
          if heroku addons:info heroku-postgresql --app ${{ secrets.HEROKU_APP_NAME }} 2>/dev/null; then
            echo "Database already exists"
          else
            echo "Creating Heroku Postgres..."
            heroku addons:create heroku-postgresql:${{ secrets.HEROKU_DB_PLAN }} --app ${{ secrets.HEROKU_APP_NAME }}
            sleep 20  # wait for Heroku to provision the DB
          fi

      - name: Convert DATABASE_URL to JDBC format
        run: |
          echo "JDBC_DATABASE_URL=$(heroku config:get DATABASE_URL --app ${{ secrets.HEROKU_APP_NAME }} | sed 's/postgres:/jdbc:postgresql:/')?sslmode=require" >> $GITHUB_ENV

      - name: Convert and Set Database Config
        run: |
          # Get Heroku's DATABASE_URL and convert to JDBC format
          DB_URL=$(heroku config:get DATABASE_URL --app ${{ secrets.HEROKU_APP_NAME }})
          JDBC_URL="jdbc:postgresql://$(echo $DB_URL | sed 's/.*@//')?sslmode=require"

          # Extract credentials
          DB_USER=$(echo $DB_URL | awk -F'://|:|@' '{print $2}')
          DB_PASS=$(echo $DB_URL | awk -F'://|:|@' '{print $3}')

          # Set all config vars
          heroku config:set \
            JDBC_DATABASE_URL="$JDBC_URL" \
            SPRING_DATASOURCE_URL="$JDBC_URL" \
            SPRING_DATASOURCE_USERNAME="$DB_USER" \
            SPRING_DATASOURCE_PASSWORD="$DB_PASS" \
            SPRING_JPA_HIBERNATE_DDL_AUTO=update \
            SERVER_PORT=$PORT \
            --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "abdulrahman403828@fci.bu.edu.eg"
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          BASE_URL: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com
          ALLOWED_ORIGINS: http://localhost:4200,https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com
          JDBC_DATABASE_URL: ${{ env.JDBC_DATABASE_URL }}